### ISSUE TITLE
ADC locking up after les then a minute trying to read multiple analog pins

### ISSUE THREAD

**Issue by seamaster101** [SMFSW/SmoothADC#2]
Hi,
I'm not sure if it's the library or the way I'm using it. 
I just posted details here:
[https://forum.arduino.cc/index.php?topic=486278.0](url)

**Comment by SMFSW** [comment]
if ((tempTime - MemTimeSerial) > 100)
This problem would remind me of an inconsistency of types when comparing them to some uint time (uint16 - uint32).

Unfortunately, I don't have Teensy board to test your code myself.
At least, I did test again SmoothADCexample on an UNO for more than 15mn now, and still getting evolution in results.

Can you come up with some more informations on your experiments on forum.arduino.cc (or here if clearly related to lib itself), so I can fix this for Teensy / any board ?
I'll try watch a little more closely at the problem later tonight.

Thanks

**Comment by seamaster101** [comment]
Hi,
I did resolve my issue today (actually it was one of the lead SW guys at work that i asked for help :)).
We did establish first that the error is in the library by printing the raw value from the ADC and monitoring if it continue to change after the output locks. The raw value was still updating...
Next step for him was to see where is the issue in the library. 
he did use some Serial.print("something"); to figure out what function was failing and established that the spillover in your "bool SmoothADC::TestAcqRate()" wasnt handled right. so when it reaches 65536 and zeros, it was failing. he wrote the following fix:


bool SmoothADC::TestAcqRate()
{
	uint16_t	tempTime = millis();
	
	uint16_t delta =  (tempTime > MemTimeAcq) ? (tempTime - MemTimeAcq) : (UINT16_MAX - (MemTimeAcq - tempTime));

	if (delta >= AcqPeriod)
	{
		MemTimeAcq = tempTime;
		return true;
	}
	
	return false;
}

Now it works fine. You might want to do another version where you address the issue. 
thanks for your time writing the library and @Chris.MonkieWicz for the quick fix today.

**Comment by seamaster101** [comment]
Found the problem. posted on Arduino andGithub explanation. Attached is the fixed file. 
its in function 
bool SmoothADC::TestAcqRate() 
{ 
uint16_t tempTime = millis(); 

uint16_t delta = (tempTime > MemTimeAcq) ? (tempTime - MemTimeAcq) : (UINT16_MAX - (MemTimeAcq - tempTime)); 

if (delta >= AcqPeriod) 
{ 
MemTimeAcq = tempTime; 
return true; 
} 

return false; 
}

**Comment by SMFSW** [comment]
Please try to serial print your delta variable when it's becoming true.... I do get a lot of wrong values considering timing (seems like it's true way too much often with an overflowed delta value).
You'll be able to see the flow on the serial terminal which is not every xxxms (try 500ms for example).

Then, Please try this instead (adding a cast to unsigned) in the TestAcqRate function.
if ((uint16_t) (tempTime - MemTimeAcq) >= AcqPeriod)

I do get pretty good results with that.

The issue seems to be related to 32bits boards, I did not experienced it on Uno board for example, but I had the issue when trying it on a Due.
It seems it compares a signed result from the substraction with an usigned value for period.

Please let me know which fix works best...
I'll make changes then, in this library, and some other libs of mine which can potentially have such related issue.

Thanks for your help trying to improve the library!

**Comment by seamaster101** [comment]
I just found another issue:
if i measure voltage with my board using the library, at around 15.9V (I use 47K and 5.6K divider) the voltage that the board prints out suddenly jumps to 16.6. This does not happen if i use simple function with read value from the pin and covert to voltage.
Can you please check for that problem too? appears that everting is fine to certain value (i read the exact voltage) but then some number gets out of range and screws up the math somewhere in the function. 
I’m not very good to write code but if you have fix I can test it.
Jordan




https://www.dropbox.com/s/6uwzmgjj5nenwhc/Screenshot%202017-06-29%2021.17.40.png?dl=0 <https://www.dropbox.com/s/6uwzmgjj5nenwhc/Screenshot%202017-06-29%2021.17.40.png?dl=0>

**Comment by SMFSW** [comment]
Open another issue for the second thing, and please help finish fixing the first one.

You may already still have a problem if using the fix you told for issue #2

Thanks

**Comment by seamaster101** [comment]
I did use 

in the TestAcqRate function
if ((uint16_t) (tempTime - MemTimeAcq) >= AcqPeriod)
 
as what you suggested and it works now. I did not experience the lockup of data after that.
Let me know if I should do some other testing to help resolve the issue.

Jordan

**Comment by SMFSW** [comment]
Even if can't exclude there's something related to the lib, it appears there are inconsistencies in your code versus readings you get.

You try to set an ADC resolution of 10 bits in your sketch (using analogReadResolution that you can put in setup function, calling it once might be enough) if unchanged since your post Jun 28, 2017, 11:17 am on arduino.cc. This means you should get values ranging from 0 to 1023.

Try to uncomment DEBUG define in SmoothADC.h, and call debug function like it's done in example, you'll get values from tabs for the channel you need, this also might help.

**Again, I invite you to open another issue if you really have a problem with the lib itself.**
The issue #2 related to timing is now closed (update will be commited to github in the next few days, giving some time for another issue to be raised if needed).
